name: Build

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_VERSION: 2018.4.18f1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          unityVersion: $UNITY_VERSION

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: $UNITY_VERSION
          targetPlatform: StandaloneWindows64

      # Upload build
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build

      # Prepare unitypackage file list
      - name: Prepare unitypackage file list
        run: |
          echo "Assets/ProceduralLevelGenerator.meta" > unitypackageFiles
          find ./Assets/ProceduralLevelGenerator/ -name \*.meta >> unitypackageFiles

      # Package files
      - uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: 'ProceduralLevelGenerator.unitypackage'
          include-files: metaList
      
      # Upload unitypackage
      - uses: actions/upload-artifact@v2-preview
        with:
          path: ProceduralLevelGenerator.unitypackage
          name: ProceduralLevelGenerator.unitypackage

